name: Build release packages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  package:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # macos-latest as soon as v1.0.0 is ready
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Create debian package on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew packageDeb

      - name: Create container packages on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          ./gradlew packageAppImage
          mkdir -p ./build/release/main/image/DXVKoTool/usr
          curl --request GET --url https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage --location --output ./build/release/main/image/appimagetool.AppImage
          curl --request GET --url https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64 --location --output ./build/release/main/image/DXVKoTool/AppRun
          chmod +x ./build/release/main/image/appimagetool.AppImage
          chmod +x ./build/release/main/image/DXVKoTool/AppRun
          cp ./DXVKoTool.desktop ./build/release/main/image/DXVKoTool/
          cp ./build/release/main/app/DXVKoTool/lib/DXVKoTool.png ./build/release/main/image/DXVKoTool/
          cp -r ./build/release/main/app/DXVKoTool/bin ./build/release/main/image/DXVKoTool/usr/
          cp -r ./build/release/main/app/DXVKoTool/lib ./build/release/main/image/DXVKoTool/usr/
          ./build/release/main/image/appimagetool.AppImage ./build/release/main/image/DXVKoTool ./build/release/main/image/DXVKoTool.AppImage
          tar cJf ./build/release/main/app/DXVKoTool.tar.xz ./build/release/main/app/DXVKoTool

      - name: Execute packaging on Windows
        if: matrix.os == 'windows-latest'
        run: gradlew.bat packageExe; gradlew.bat packageMsi
        working-directory: ${{ github.workspace }}

      - name: Execute packaging on Mac
        if: matrix.os == 'macos-latest'
        run: ./gradlew packageDmg; ./gradlew packagePkg

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/release/main/app/DXVKoTool.tar.xz
            ./build/release/main/image/DXVKoTool.AppImage
            ./build/release/main/deb/*.deb
            ./build/release/main/exe/*.exe
            ./build/release/main/msi/*.msi
            ./build/release/main/dmg/*.dmg
            ./build/release/main/pkg/*.pkg
