name: Build release packages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  package:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # macos-latest as soon as v1.0.0 is ready
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute packaging on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew packageDeb; ./gradlew packageAppImage && cd ./build/release/main/app/ && tar cJf DXVKoTool.tar.xz DXVKoTool

      - name: Execute packaging on Windows
        if: matrix.os == 'windows-latest'
        run: gradlew packageExe; gradlew packageMsi

      - name: Execute packaging on Mac
        if: matrix.os == 'macos-latest'
        run: ./gradlew packageDmg; ./gradlew packagePkg

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/release/main/app/DXVKoTool.tar.xz
            ./build/release/main/deb/*.deb
            ./build/release/main/exe/*.exe
            ./build/release/main/msi/*.msi
            ./build/release/main/dmg/*.dmg
            ./build/release/main/pkg/*.pkg
